### ISSUE TITLE
CircleCI on master not stable [2]

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang-content#364] opened 2015-09-25 08:10 UTC
https://circleci.com/gh/CloudSlang/cloud-slang-content/tree/master

**Comment by meirwah** [comment] 2015-10-04 09:30
@gituser173 CircleCI seems unstable.. on many PR, please look into this...

**Comment by meirwah** [comment] 2015-10-04 09:31
https://circleci.com/gh/CloudSlang/cloud-slang-content/1911

**Comment by gituser173** [comment] 2015-10-05 08:53
https://circleci.com/gh/CloudSlang/cloud-slang-content/1911
Looks like the "com.jcraft.jsch.JSchException: session is down" exception is found in this log. Maybe the code that fixes this issue is not on this branch? This was fixed in master.

**Comment by Bonczidai** [comment] 2015-10-05 09:02
you can merge from master into that branch, push it and see if it is reproduced

**Comment by gituser173** [comment] 2015-10-05 12:29
Most of the errors from the master https://circleci.com/gh/CloudSlang/cloud-slang-content/tree/master are related to https://github.com/CloudSlang/score-actions/issues/74 which is fixed by @Bonczidai in https://github.com/CloudSlang/score-actions/pull/79. Also there are some exceptions that might be caused by network errors. Also merged from master for https://circleci.com/gh/CloudSlang/cloud-slang-content/1911 and the "session is down" is still there. I will continue investigating

**Closed** 2015-10-08 06:25 UTC
Labels: bug
