### ISSUE TITLE
Update content: align metadata section with builder validation

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang-content#793] opened 2016-09-12 13:24 UTC
as per https://github.com/CloudSlang/cloud-slang/issues/821 - Builder: add flag to validate description section against actual inputs

we need to update the content so for new contributions it will be easier to run the tool and verify description section

**Comment by tethryus** [comment] 2016-09-22 06:53
@Bonczidai I have tested the impact of having to align the content with the new builder validations and this change will have a positive impact overall. After this change, every operation or flow, will have to follow the guidelines and will ensure that every operation/flow or decision will be working as intended. New contributors will have a better understanding of why and how to create content.

**Comment by tethryus** [comment] 2016-09-26 14:39
@Bonczidai Content metadata has been updated with builder validation, Content merged. Issue can be closed.

**Closed** 2016-09-26 14:42 UTC
